# Generated by Django 4.1.7 on 2023-08-09 09:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reporting', '__first__'),
        ('import_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('status', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('is_recurring', models.BooleanField(default=False)),
                ('m_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meeting',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingRecurringMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings_for_recurring_meetings', to='minutes_of_meeting.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('cron', models.CharField(blank=True, max_length=250, null=True)),
                ('start_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('end_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('meetings', models.ManyToManyField(through='minutes_of_meeting.MeetingRecurringMeeting', to='minutes_of_meeting.meeting')),
            ],
            options={
                'verbose_name': 'RecurringMeeting',
                'verbose_name_plural': 'RecurringMeeting',
            },
        ),
        migrations.CreateModel(
            name='Perticular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
                ('completion_date', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('cron', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_for_perticular', to=settings.AUTH_USER_MODEL)),
                ('reminder', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_for_task', to='reporting.celeryscheduletask')),
            ],
            options={
                'verbose_name': 'Perticular',
                'verbose_name_plural': 'Perticular',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('is_organizer', models.BooleanField(default=False)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendee_for_attendence', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_for_thread', to='import_app.company')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_for_meeting_thread', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MeetingThread',
                'verbose_name_plural': 'MeetingThreads',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='meetingrecurringmeeting',
            name='recurring_meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_meeting', to='minutes_of_meeting.recurringmeeting'),
        ),
        migrations.CreateModel(
            name='MeetingPerticular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='minutes_of_meeting.meeting')),
                ('perticular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perticulars', to='minutes_of_meeting.perticular')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='attendee',
            field=models.ManyToManyField(blank=True, related_name='attendee_for_meeting', to='minutes_of_meeting.meetinguser'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_thread_for_meeting', to='minutes_of_meeting.meetingthread'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='perticular',
            field=models.ManyToManyField(through='minutes_of_meeting.MeetingPerticular', to='minutes_of_meeting.perticular'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='reminder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_for_meeting', to='reporting.celeryscheduletask'),
        ),
    ]
